### ISSUE TITLE
[autowrap 0.6.0] Tests not generated and failed with Python3

### ISSUE THREAD

**Issue by sagitter** [uweschmitt/autowrap#19]
Hi all.

There are some tests not generated under Python3.4
```
gcc -pthread -Wno-unused-result -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/usr/include/boost -fPIC -I/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/data_files/boost -I/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/data_files -I/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/tests/test_files -I/usr/include/python3.4m -c shared_ptr_test.cpp -o build/temp.linux-x86_64-3.4/shared_ptr_test.o -Wno-unused-but-set-variable
g++ -pthread -shared -Wl,-z,relro -I/usr/include/boost build/temp.linux-x86_64-3.4/shared_ptr_test.o -L/usr/lib64 -lpython3.4m -o /tmp/tmp5thjld4a/m.cpython-34m.so
ok
tests.test_code_generator.test_libcpp ... ERROR
tests.test_code_generator.test_stl_libcpp ... ERROR
tests.test_code_generator.test_minimal ... ERROR
tests.test_code_generator.test_templated ... ERROR
tests.test_cython_build_process.testBuildExt ... running build_ext
cythoning itertest.pyx to itertest.cpp
```

Full log (starting from line #393): http://fpaste.org/183011/

**Comment by hroest** [comment]
The issue looks like the same one in #17 which I addressed in the pull request #18 

Can you try to add the patch from #18 and see whether this fixes the problem?

The output seems to choke on this, which should be addressed in #18
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/tests/test_code_generator.py", line 57, in test_number_conv
    root=test_files, target=target,  debug=True)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/__init__.py", line 80, in parse_and_generate_code
    extra_cimports)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/__init__.py", line 62, in generate_code
    extra_cimports)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/CodeGenerator.py", line 117, in __init__
    self.cr = setup_converter_registry(self.classes, self.enums, instance_mapping)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/ConversionProvider.py", line 1474, in setup_converter_registry
    names_of_enums_to_wrap)
  File "/home/sagitter/rpmbuild/BUILD/python3-autowrap-0.6.0-1.20150121git75e9a5.fc21/autowrap/ConversionProvider.py", line 83, in __init__
    self.names_of_wrapper_classes += ["const %s" % k for k in instance_mapping.keys()]
nose.proxy.TypeError: unsupported operand type(s) for +=: 'dict_keys' and 'list'
```
