### ISSUE TITLE
std::move in autowrap

### ISSUE THREAD

**Issue by oliveralka** [uweschmitt/autowrap#95]
Cython has `std::move` support since version 0.29.17 (https://github.com/cython/cython/pull/3358).

I was trying to wrap a new function from the [SiriusAdapterAlgorithm](https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/SiriusAdapterAlgorithm.pxd) (OpenMS) via autowrap which looks like this:
```
...
from libcpp.utility cimport move
...
libcpp_vector[String] sortSiriusWorkspacePathsByScanIndex(libcpp_vector[String]&& subdirs) nogil except +
```

Building pyopenms fails with the following traceback:
```
Traceback (most recent call last):
  File "create_cpp_extension.py", line 63, in <module>
    decls, instance_map = autowrap.parse(pxd_files, ".", num_processes=int(PY_NUM_THREADS))
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/__init__.py", line 51, in parse
    return DeclResolver.resolve_decls_from_files(files, root, num_processes)
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 239, in resolve_decls_from_files
    return resolve_decls_from_files_single_thread(pathes, root)
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/DeclResolver.py", line 232, in resolve_decls_from_files_single_thread
    decls.extend(PXDParser.parse_pxd_file(full_path))
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 487, in parse_pxd_file
    result.append(handler(body, lines, path))
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 288, in parseTree
    decl = MethodOrAttributeDecl.parseTree(att, lines, pxd_path)
  File "/usr/local/miniconda3/envs/build_pyopenms_38/lib/python3.8/site-packages/autowrap/PXDParser.py", line 390, in parseTree
    argname = argdecl.base.name
AttributeError: 'CReferenceDeclaratorNode' object has no attribute 'name'
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp] Error 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms_create_cpp.dir/all] Error 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/rule] Error 2
make: *** [pyopenms] Error 2
```

Is this functionality currently available in autowrap and/or does someone has experience with it?

**Comment by oliveralka** [comment]
Actually, this is a bad example since the rvalue reference should not be used in this fashion. 
Will close this issue, since this is not a valid use case.
